name: Deploy static site with nested index.html

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Copy required folders into templates/
        run: |
          mkdir -p src/templates/assets
          mkdir -p src/templates/scripts
          mkdir -p src/templates/styles
          cp -r src/assets/* src/templates/assets/
          cp -r src/scripts/* src/templates/scripts/
          cp -r src/styles/* src/templates/styles/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/templates

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
